<a href="https://colab.research.google.com/github/dikshanaik/TA1/blob/master/IA3_Diksha_Naik.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [565]:
import numpy as np
import re
import scipy as sp
import pandas as pd
import sklearn as sk
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [566]:
data = pd.read_csv("https://raw.githubusercontent.com/AnoVando/MSIS/master/IA3.csv")

data.head()

id                                             review       label
0   1  About the shop: There is a restaurant in Soi L...  restaurant
1   2  About the shop: Through this store for about t...  restaurant
2   3  Roast Coffee &amp; Eatery is a restaurant loca...  restaurant
3   4  Eat from the children. The shop is opposite. P...  restaurant
4   5  The Ak 1 shop at another branch tastes the sam...  restaurant

In [567]:
data.isnull().any()

id        False
review    False
label     False
dtype: bool

In [0]:
reviewData = data["review"].tolist()

In [569]:
#Tokanize Step 1
token_review =[]
for i in reviewData:
  #print(i)
  token= nltk.word_tokenize(i)
  token_review.append(token)

print(token_review)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [570]:
print(token_review[0])

['About', 'the', 'shop', ':', 'There', 'is', 'a', 'restaurant', 'in', 'Soi', 'Langsuan', '(', 'Road', ')', 'inside', 'of', 'Luxx', 'Hotel', '.', 'The', 'décor', 'of', 'the', 'restaurant', ':', 'decorated', 'in', 'a', 'rustic', 'style', ',', 'white', 'walls', ',', 'glass', 'tables', ',', 'red', 'chairs', ',', 'parquet', 'floors', ',', 'dim', 'lights', 'open', 'at', 'night', ',', 'the', 'romantic', 'atmosphere', ':', 'Duck', 'l', '&', '#', '39', ';', 'orange', 'Pork', 'Wellington', 'and', 'French', 'onion', 'soup', '.', 'Average', 'Price', ':', '250-450', 'Baht', 'Food', 'Review', ':', 'Duck', 'l', '&', '#', '39', ';', 'orange', '(', '455', ')', 'Duck', 'breast', 'sliced', 'Pork', 'Wellington', '(', '445', ')', 'is', 'a', 'piece', 'of', 'tender', 'pork', 'stuffed', 'with', 'stuffing', 'and', 'wrapped', 'in', 'a', 'thin', 'pastry', 'and', 'then', 'baked', 'to', 'serve', 'with', 'the', 'sauce', '.', 'Duck', 'roll', '(', '285', ')', 'is', 'a', 'Duck', 'wrapped', 'with', 'vegetables', 'and',

In [571]:
#Lemmetize Step 1
lem_review = []
lemmatizer = nltk.stem.WordNetLemmatizer()
for i in token_review:
  lemmatized_review = [lemmatizer.lemmatize(x) for x in i if x.isalpha()]
  lem_review.append(lemmatized_review)
print(lem_review)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [572]:
print(lem_review[0])

['About', 'the', 'shop', 'There', 'is', 'a', 'restaurant', 'in', 'Soi', 'Langsuan', 'Road', 'inside', 'of', 'Luxx', 'Hotel', 'The', 'décor', 'of', 'the', 'restaurant', 'decorated', 'in', 'a', 'rustic', 'style', 'white', 'wall', 'glass', 'table', 'red', 'chair', 'parquet', 'floor', 'dim', 'light', 'open', 'at', 'night', 'the', 'romantic', 'atmosphere', 'Duck', 'l', 'orange', 'Pork', 'Wellington', 'and', 'French', 'onion', 'soup', 'Average', 'Price', 'Baht', 'Food', 'Review', 'Duck', 'l', 'orange', 'Duck', 'breast', 'sliced', 'Pork', 'Wellington', 'is', 'a', 'piece', 'of', 'tender', 'pork', 'stuffed', 'with', 'stuffing', 'and', 'wrapped', 'in', 'a', 'thin', 'pastry', 'and', 'then', 'baked', 'to', 'serve', 'with', 'the', 'sauce', 'Duck', 'roll', 'is', 'a', 'Duck', 'wrapped', 'with', 'vegetable', 'and', 'dough', 'wrap', 'not', 'much', 'delicious', 'French', 'onion', 'soup', 'Sweet', 'taste', 'Garnish', 'with', 'cheese', 'Bake', 'Scallop', 'is', 'a', 'scallop', 'in', 'a', 'thick', 'cream', 

In [573]:
#remove stopwords Step 1
from nltk.corpus import stopwords
stopWordEnglish = stopwords.words('english')
stopword_list=['I','l','lt','gt','quot','wa','ha','Ourselves','Hers','Between','Yourself','But','Again','There','About','Once',
               'During','Out','Very','Having','With','They','Own','an','Be','Some','For','Do', 'Its', 'Yours', 'Such', 'Into',
               'Of', 'Most', 'Itself', 'Other', 'Off', 'Is', 'S', 'Am', 'Or', 'Who', 'As', 'From', 'Him', 'Each', 'The', 'Themselves',
               'Until', 'Below', 'Are', 'We', 'These', 'Your', 'His', 'Through', 'Don', 'Nor', 'Me', 'Were', 'Her', 'More', 'Himself',
               'This', 'Down', 'Should', 'Our', 'Their', 'While', 'Above', 'Both', 'Up', 'To', 'Ours', 'Had', 'She', 'All', 'No', 'When',
               'At', 'Any', 'Before', 'Them', 'Same', 'And', 'Been', 'Have', 'In', 'Will', 'On', 'Does', 'Yourselves', 'Then', 'That', 'Because',
               'What', 'Over', 'Why', 'So', 'Can', 'Did', 'Not', 'Now', 'Under', 'He', 'You', 'Herself', 'Has', 'Just', 'Where', 'Too', 'Only',
               'Myself', 'which', 'those', 'After', 'Few', 'Whom', 'T', 'Being', 'If', 'Theirs', 'My', 'Against', 'A', 'By', 'Doing', 'It', 'How',
               'Further', 'Was', 'Here', 'Than', 'Also','also']
stopWordEnglish.extend(stopword_list)
stop_words = []

for stop in lem_review:
  stop_words_removed = [x for x in stop if x not in stopWordEnglish]
  stop_words.append(stop_words_removed)
  
print(stop_words)

[['shop', 'restaurant', 'Soi', 'Langsuan', 'Road', 'inside', 'Luxx', 'Hotel', 'décor', 'restaurant', 'decorated', 'rustic', 'style', 'white', 'wall', 'glass', 'table', 'red', 'chair', 'parquet', 'floor', 'dim', 'light', 'open', 'night', 'romantic', 'atmosphere', 'Duck', 'orange', 'Pork', 'Wellington', 'French', 'onion', 'soup', 'Average', 'Price', 'Baht', 'Food', 'Review', 'Duck', 'orange', 'Duck', 'breast', 'sliced', 'Pork', 'Wellington', 'piece', 'tender', 'pork', 'stuffed', 'stuffing', 'wrapped', 'thin', 'pastry', 'baked', 'serve', 'sauce', 'Duck', 'roll', 'Duck', 'wrapped', 'vegetable', 'dough', 'wrap', 'much', 'delicious', 'French', 'onion', 'soup', 'Sweet', 'taste', 'Garnish', 'cheese', 'Bake', 'Scallop', 'scallop', 'thick', 'cream', 'cheese', 'Serve', 'thin', 'toast', 'eat', 'together', 'Score', 'topic', 'Atmosphere', 'Atmosphere', 'nice', 'romantic', 'food', 'taste', 'Service', 'Good', 'service', 'good', 'food', 'recommendation', 'Value', 'price', 'quite', 'expensive', 'baht', 

In [545]:
###Vectorize with Bigram Step 1 
from sklearn.feature_extraction.text import CountVectorizer

input2 = [" ".join(x) for x in stop_words]

count = CountVectorizer(ngram_range=(2, 2), min_df=5)
count.fit(input2)
v2 = count.transform(input2)
terms = count.get_feature_names()
print(terms)
print(count.vocabulary_)
print('\n')
print(v2.toarray())


['acting skill', 'action film', 'action movie', 'add little', 'add lot', 'addition film', 'advantage disadvantage', 'air room', 'almost every', 'along way', 'although film', 'although know', 'although many', 'although plot', 'although still', 'although story', 'always feel', 'always felt', 'always make', 'always people', 'always think', 'always thought', 'american drama', 'american movie', 'ancient time', 'animated film', 'another menu', 'another place', 'another point', 'anything else', 'around world', 'art film', 'atmosphere good', 'atmosphere nice', 'atmosphere restaurant', 'atmosphere shop', 'audience like', 'audience watching', 'average price', 'award best', 'back eat', 'back home', 'back try', 'background story', 'bad film', 'bad guy', 'bad thing', 'baht delicious', 'baht dish', 'baht eat', 'baht menu', 'baht per', 'bai fumei', 'bass fish', 'battle film', 'battle stalingrad', 'beautiful love', 'beautiful picture', 'beautiful thing', 'beautiful woman', 'beautifully decorated', 'be

In [546]:
#Step 2 LDA with 6 topics
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components=6).fit(v2)

for topic_idx,topic in enumerate(lda.components_):
    print(f'Topic #{topic_idx}:')
    print(" ".join([terms[i] for i in topic.argsort()[:-6-1:-1]]))
    print('\n')


Topic #0:
box office hong kong horror film make people blind date many people


Topic #1:
tv drama year old river lake love love every day ten year


Topic #2:
taste good delicious food good service da ming atmosphere good stir fried


Topic #3:
real estate many people pay attention every day human body long time


Topic #4:
elf hostel united states many people make people three people people feel


Topic #5:
ice cream green tea like eat want eat fried rice price baht




In [547]:
#Step 3 Food review topic distribution with top-2 topics
f1=lda.transform(v2[1])
f2=lda.transform(v2[2])
f3=lda.transform(v2[3])
f4=lda.transform(v2[4])
f5=lda.transform(v2[5])
f6=lda.transform(v2[6])
f7=lda.transform(v2[7])
f8=lda.transform(v2[8])
f9=lda.transform(v2[9])
f10=lda.transform(v2[10])
print(f1)
print(f2)
print(f3)
print(f4)
print(f5)
print(f6)
print(f7)
print(f8)
print(f9)
print(f10)

[[0.00560926 0.00560815 0.97188599 0.00562009 0.00569397 0.00558255]]
[[0.00595648 0.00596618 0.00602724 0.00597023 0.00595915 0.97012073]]
[[0.02396635 0.02393598 0.50044026 0.02396094 0.02381912 0.40387734]]
[[0.02777792 0.0277779  0.2121641  0.02785111 0.02783749 0.67659148]]
[[0.00574748 0.00574831 0.7117897  0.04306907 0.005762   0.22788344]]
[[0.0139535  0.01394508 0.49707627 0.01397445 0.16634603 0.29470468]]
[[0.00757639 0.00757625 0.47384464 0.00758135 0.00758993 0.49583144]]
[[0.0416667  0.04166669 0.79153822 0.04166672 0.04167273 0.04178893]]
[[0.05571907 0.38874301 0.05599386 0.05555622 0.05555602 0.38843182]]
[[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]]


**Based on the topic distributions, the top 2 topics are 3 & 6**

In [548]:
 #Step 3 Movie Review topic distribution with top-2 topics
m1=lda.transform(v2[501])
m2=lda.transform(v2[502])
m3=lda.transform(v2[503])
m4=lda.transform(v2[504])
m5=lda.transform(v2[505])
m6=lda.transform(v2[506])
m7=lda.transform(v2[507])
m8=lda.transform(v2[508])
m9=lda.transform(v2[509])
m10=lda.transform(v2[510])
print(m1)
print(m2)
print(m3)
print(m4)
print(m5)
print(m6)
print(m7)
print(m8)
print(m9)
print(m10)

[[0.00764167 0.00761603 0.00760079 0.96187449 0.00766573 0.0076013 ]]
[[0.28303619 0.36204207 0.0064157  0.12767448 0.21440366 0.0064279 ]]
[[0.08333361 0.08333358 0.08333374 0.58333174 0.08333367 0.08333367]]
[[0.15833296 0.80816088 0.00838493 0.00838626 0.00840155 0.00833342]]
[[0.01675451 0.45592003 0.01672492 0.3034834  0.19042914 0.016688  ]]
[[0.01294329 0.12960377 0.01282193 0.24544574 0.58635562 0.01282965]]
[[0.08403131 0.5826322  0.08333414 0.0833343  0.08333405 0.083334  ]]
[[0.91242566 0.07043619 0.00427444 0.00429783 0.00429178 0.0042741 ]]
[[0.98174216 0.00367794 0.00362496 0.00364616 0.0036646  0.00364418]]
[[0.26716921 0.64921325 0.02083354 0.0209065  0.02104084 0.02083666]]


**Based on the topic distribution, top-2 topics are 2 & 4**

In [0]:
#Step 4 using Unigram to get 5 words
input3 = [" ".join(x) for x in stop_words]

#print(input3)

top5 = CountVectorizer(ngram_range=(1, 1), min_df=5)
top5.fit(input3)
v3 = top5.transform(input3)
features = top5.get_feature_names()


In [577]:
lda_top5 = LatentDirichletAllocation(n_components=6).fit(v3)

for topic_idx,topic in enumerate(lda_top5.components_):
    print(f'Topic #{topic_idx}:')
    print(" ".join([features[i] for i in topic.argsort()[:-5-1:-1]]))
    print('\n')


Topic #0:
love film story song lin


Topic #1:
cake shop good atmosphere coffee


Topic #2:
eat good delicious like food


Topic #3:
people life like time love


Topic #4:
book people love woman life


Topic #5:
film movie story war people




**Topic 1 is mostly a movie review about a love story film, 
Topic 2 is mostly a food review about cake & coffee, 
Topic 3 is mostly a food review about delicious food, 
Topic 4 is mostly a movie review about love film, 
Topic 5 is mostly a movie review about woman oriented or book inspired film, 
Topic 6 is mostly a movie review about war film** 

In [578]:
#Step 5
review1=lda_top5.transform(v3[1])
review501=lda_top5.transform(v3[501])
print(review1)
print(review501)

[[0.00155358 0.46089636 0.53288129 0.00155378 0.00155379 0.0015612 ]]
[[6.61451980e-04 6.62648126e-04 7.68134986e-02 6.82911187e-01
  6.63791758e-04 2.38287422e-01]]


**Based on step 3 & 4, review 1 is about a Restaurant review & review 501 is is about a Movie review**